# Site settings
baseurl = "http://dustinbennett.net/"
languageCode = "en-us"
title = "Dustin Bennett"
theme = "hugo-freelancer-theme-custom"


[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Dustin Bennett"
    description = "Personal site"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email youself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    email = "dustin@dustinbennett.net"

    [params.navigation]
        brand = "Dustin Bennett"


    [params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "CircleHeadshot.png"
        name = "Dustin Bennett"
        subtitle = "Technology - Strategy - Operations"


    [params.portfolio]
        # All projects defined in their own files. You can find example projects
        # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
        # at the root of this Hugo site.
        # For more informtion take a look at the README.
        title = "Experience"

        [params.portfolio.modal]
            client = "Company"
            date = "Time range"
            category = "Skills"
            buttontext = "Close"


    [params.about]
        title = "About"
        # TODO: fill in this text
        left = "Intellectually curious technical leader with proven track record in startup and large enterprise environments. Extensive experience in cloud and mobile technologies. Passion for efficiency and continuous improvement."
        right = "Adept at consensus building, influencing without authority, and negotiations. Leader for digital transformation and move to internal and public cloud. "

#    [params.contact]
#        title = "Contact"

        # 'error' defines error messages for invalid inputs
#        [params.contact.form.name]
#            text = "Name"
#            error = "Please enter your name."

#        [params.contact.form.email]
#            text = "Email Address"
#            error = "Please enter your email address."

#        [params.contact.form.phone]
#            text = "Phone Number"
#            error = "Please enter your phone number."

#        [params.contact.form.message]
#            text = "Message"
#            error = "Please enter a message."

#        [params.contact.form.button]
#            text = "Send"


    [params.footer]
        copyright = ""

        [params.footer.location]
            title = "Location"
            # Postal address (add as many lines as necessary)
            address = ["Boston, MA"]

        [params.footer.social]
            title = "Around the web"
            # TODO: update with social links
            [[params.footer.social.networks]]
                icon = "fa-github"
                link = "https://github.com/dusbennett"

            [[params.footer.social.networks]]
                icon = "fa-stack-overflow"
                link=  "https://stackoverflow.com/users/593014/dusbennett"


            [[params.footer.social.networks]]
                icon = "fa-linkedin"
                link=  "https://www.linkedin.com/in/dusbennett/"


            [[params.footer.social.networks]]
                icon = "fa-twitter"
                link=  "https://twitter.com/dusbennett"

        #[params.footer.credits]
        #    title = "About Site"
        #    text = "Built using Hugo Freelancer Theme. Icons made by [Freepik](http://www.freepik.com) from [Flaticon](http://www.flaticon.com) is licensed by [CC 3.0 BY](http://creativecommons.org/licenses/by/3.0/)"
